In [1]:
%%time
import pandas as pd
import numpy as np
data=pd.read_csv(r'D:\Projects\Goods_prediction\real_data\data2020.csv',decimal=',',
                dtype={'DiscountCardId':np.int32,'goodsid':np.int32,'GoodsGroup2Id':np.int16,'GoodsGroup1Id':np.int16,
                        'Warehouseid':np.int16,'creditgroupid':np.int64,'Quantity':np.float32,'summ':np.float32},sep=';')
data=data.drop(['GoodsGroup2Id'],axis=1)
#data=data.rename(columns={'GoodsGroup2Id':'GoodsGroup3Id'})
data['CreditGroupTime']=pd.to_datetime(data['CreditGroupTime'])
#data['weekofmonth']=data['CreditGroupTime'].dt.week/(data['CreditGroupTime'].dt.month+1)
goods=pd.read_csv(r'D:\Projects\Goods_prediction\real_data\goods1id.csv',engine='python',sep=';',names=['GoodsGroup1Id','goodsname'])
goods['GoodsGroup1Id']=goods['GoodsGroup1Id'].astype(int)
data=data.merge(goods.reset_index(drop=False),how='left',on='GoodsGroup1Id')
data=data.drop(['goodsname'],axis=1)
data=data.rename(columns={'index':'GoodsGroup3Id'})
data=data.dropna().reset_index(drop=True)
data['GoodsGroup3Id']=data['GoodsGroup3Id'].astype(np.int32)
data=data.sort_values('creditgroupid').reset_index(drop=True)
data
# goods=pd.read_csv(r'D:\Projects\Goods_prediction\real_data\goods1id.csv',engine='python',sep=';',names=['GoodsGroup1Id','goodsname'])
# goods['GoodsGroup1Id']=goods['GoodsGroup1Id'].astype(int)
# goods=pd.read_csv(r'D:\Projects\Goods_prediction\real_data\goods1id.csv',engine='python',sep=';',names=['GoodsGroup1Id','goodsname'])
# goods['GoodsGroup1Id']=goods['GoodsGroup1Id'].astype(int)
# data=data.merge(goods.reset_index(drop=False),how='left',on='GoodsGroup1Id')
# data=data.drop(['goodsname'],axis=1)
# data=data.rename(columns={'index':'GoodsGroup3Id'})
# # #data=data.dropna().reset_index(drop=True)
# data['GoodsGroup3Id']=data['GoodsGroup3Id'].astype(np.int16)

Wall time: 6min 50s

,DiscountCardId,CreditGroupTime,goodsid,GoodsGroup1Id,Warehouseid,creditgroupid,Quantity,summ,GoodsGroup3Id
0,10707461,2018-06-01 08:05:49,353852,2629,33,1911422041,1.000,1.890000,216
1,1952459,2018-06-01 08:06:51,182415,2615,464,1911422148,1.000,0.990000,212
2,1952459,2018-06-01 08:06:51,471143,2694,464,1911422148,1.000,0.750000,239
3,9213971,2018-06-01 08:06:57,97355,5470,464,1911422154,0.678,2.320000,1830
4,9213971,2018-06-01 08:06:57,263775,2434,464,1911422154,0.193,1.350000,125
5,9476356,2018-06-01 08:06:44,779758,2841,359,1911422255,1.000,1.090000,295
6,9476356,2018-06-01 08:06:44,225503,2277,359,1911422255,1.000,6.990000,74
7,14135884,2018-06-01 08:02:59,556218,2203,286,1911422407,1.000,1.970000,34
8,14135884,2018-06-01 08:02:59,496629,2822,286,1911422407,1.000,0.450000,293
9,14135884,2018-06-01 08:02:59,31112,2751,286,1911422407,1.000,2.150000,258
10,14135884,2018-06-01 08:02:59,485146,2758,286,1911422407,1.000,0.590000,265
11,14135884,2018-06-01 08:02:59,485146,2758,286,1911422407,1.000,0.590000,265
12,14135884,2018-06-01 08:02:59,45557,2822,286,1911422407,1.000,0.450000,293
13,14135884,2018-06-01 08:02:59,556218,2203,286,1911422407,1.000,1.970000,34
14,14135884,2018-06-01 08:02:59,496629,2822,286,1911422407,1.000,0.450000,293
15,14135884,2018-06-01 08:02:59,45557,2822,286,1911422407,1.000,0.450000,293
16,1833892,2018-06-01 08:13:41,64891,2873,464,1911423088,1.000,3.090000,308
17,1833892,2018-06-01 08:13:41,418461,2581,464,1911423088,1.000,3.790000,198
18,1833892,2018-06-01 08:13:41,413657,2579,464,1911423088,1.000,1.990000,197
19,1833892,2018-06-01 08:13:41,418461,2581,464,1911423088,1.000,3.790000,198
20,1833892,2018-06-01 08:13:41,32282,5563,464,1911423088,1.000,0.530000,1904
21,1833892,2018-06-01 08:13:41,32282,5563,464,1911423088,1.000,0.530000,1904
22,13524244,2018-06-01 08:13:41,45317,2629,16800,1911423773,24.000,15.840000,216
23,13524244,2018-06-01 08:13:41,53755,2313,16800,1911423773,6.000,17.940001,92
24,13524244,2018-06-01 08:13:41,12085,2627,16800,1911423773,24.000,15.840000,215
25,13524244,2018-06-01 08:13:41,12196,2629,16800,1911423773,12.000,9.360000,216
26,13524244,2018-06-01 08:13:41,553359,2635,16800,1911423773,6.000,6.900000,221
27,13524244,2018-06-01 08:13:41,556299,2327,16800,1911423773,6.000,7.800000,94
28,13524244,2018-06-01 08:13:41,12081,2635,16800,1911423773,6.000,11.640000,221
29,13524244,2018-06-01 08:13:41,91969,2327,16800,1911423773,6.000,18.780001,94
...,...,...,...,...,...,...,...,...,...
229638136,577367,2019-09-01 20:10:57,703168,2931,625,2436833136,1.000,3.420000,344
229638137,10042714,2019-09-01 20:14:33,428337,5464,625,2436833152,1.882,1.110000,1824
229638138,10042714,2019-09-01 20:14:33,316618,3258,625,2436833152,0.656,5.040000,432
229638139,10042714,2019-09-01 20:14:33,67391,4751,625,2436833152,1.000,2.560000,1300
229638140,10042714,2019-09-01 20:14:33,87126,5490,625,2436833152,1.964,2.790000,1848
229638141,10042714,2019-09-01 20:14:33,14090,2482,625,2436833152,1.000,2.190000,154
229638142,10042714,2019-09-01 20:14:33,81920,5462,625,2436833152,3.166,1.870000,1822
229638143,10042714,2019-09-01 20:14:33,404330,5125,625,2436833152,0.304,1.410000,1620
229638144,10042714,2019-09-01 20:14:33,404330,5125,625,2436833152,0.304,1.410000,1620
229638145,10042714,2019-09-01 20:14:33,788411,2791,625,2436833152,1.000,1.130000,276
229638146,10042714,2019-09-01 20:14:33,296327,2881,625,2436833152,0.727,3.120000,313
229638147,10042714,2019-09-01 20:14:33,154238,2876,625,2436833152,1.000,0.890000,310
229638148,10042714,2019-09-01 20:14:33,154238,2876,625,2436833152,1.000,0.890000,310
229638149,10042714,2019-09-01 20:14:33,154238,2876,625,2436833152,1.000,0.890000,310
229638150,10042714,2019-09-01 20:14:33,877165,4091,625,2436833152,31.000,3.720000,662
229638151,10042714,2019-09-01 20:14:33,123115,4311,625,2436833152,1.000,2.650000,869
229638152,10042714,2019-09-01 20:14:33,793142,4122,625,2436833152,2.000,1.240000,693
229638153,10042714,2019-09-01 20:14:33,863754,2808,625,2436833152,1.000,1.380000,284
229638154,10042714,2019-09-01 20:14:33,154238,2876,625,2436833152,1.000,0.890000,310
229638155,10042714,2019-09-01 20:14:33,774061,2870,625,2436833152,1.000,2.590000,306
229638156,10042714,2019-09-01 20:14:33,908797,4075,625,2436833152,1.000,2.650000,646
229638157,10042714,2019-09-01 20:14:33,154238,2876,625,2436833152,1.000,0.890000,310
229638158,16389892,2019-09-01 20:17:57,378799,2815,625,2436833159,1.000,0.290000,291
229638159,16389892,2019-09-01 20:17:57,428465,5421,625,2436833159,2.000,1.580000,1814
229638160,16389892,2019-09-01 20:17:57,15459,2778,625,2436833159,1.000,0.770000,272
229638161,16389892,2019-09-01 20:17:57,428465,5421,625,2436833159,2.000,1.580000,1814
229638162,16389892,2019-09-01 20:17:57,15459,2778,625,2436833159,1.000,0.770000,272
229638163,16389892,2019-09-01 20:17:57,634332,2791,625,2436833159,1.000,1.230000,276
229638164,9844992,2019-09-01 20:40:48,774061,2870,625,2436833214,1.000,2.590000,306
229638165,9844992,2019-09-01 20:40:48,911715,5566,625,2436833214,1.000,1.450000,1907

In [2]:
%%time
from scipy.stats.mstats import mode
def freq(data):
    freq=mode(data.values)
    return freq[0]
def get_new_columns(name,aggs):
    itog=[]
    for k in aggs.keys():
        for agg in aggs[k]:
            if isinstance(agg,str):
                itog.append(name + '_' + k + '_' + agg)
            else:
                itog.append(name + '_' + k + '_' + agg.__name__)
    return itog
def second_freq(data):
    try:
        freq=data.value_counts().index[1]
    except IndexError:
        freq=None
    return freq
def third_freq(data):
    try:
        freq=data.value_counts().index[2]
    except IndexError:
        freq=None
    return freq
def reduce_mem_usage(df, verbose=True):
    numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
    start_mem = df.memory_usage().sum() / 1024**2    
    for col in df.columns:
        col_type = df[col].dtypes
        if col_type in numerics:
            c_min = df[col].min()
            c_max = df[col].max()
            if str(col_type)[:3] == 'int':
                if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:
                    df[col] = df[col].astype(np.int8)
                elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
                    df[col] = df[col].astype(np.int16)
                elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
                    df[col] = df[col].astype(np.int32)
                elif c_min > np.iinfo(np.int64).min and c_max < np.iinfo(np.int64).max:
                    df[col] = df[col].astype(np.int64)  
            else:
                if c_min > np.finfo(np.float16).min and c_max < np.finfo(np.float16).max:
                    df[col] = df[col].astype(np.float16)
                elif c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
                    df[col] = df[col].astype(np.float32)
                else:
                    df[col] = df[col].astype(np.float64)    
    end_mem = df.memory_usage().sum() / 1024**2
    if verbose: print('Mem. usage decreased to {:5.2f} Mb ({:.1f}% reduction)'.format(end_mem, 100 * (start_mem - end_mem) / start_mem))
    return df
def all_features(data):
    args={'creditgroupid':['nunique'],
          'Warehouseid':['nunique'],
          'WarehouseTypeId':[freq],
          'goodsid':['count'],
          'GoodsGroup3Id':[freq,second_freq,third_freq],
          'summ':['sum','mean'],
          'CreditGroupTime':['last'],
          'weekday':[freq],
          'weekend':['mean'],
          'hour':[freq,'std','max','min'],
          'day':['mean']
          
         }
    last_data=data['CreditGroupTime'].max()
    new_columns=get_new_columns('all',args)
    data=data.groupby('DiscountCardId').agg(args)
    data.columns=new_columns
    data.reset_index(drop=False,inplace=True)
    data['all_goods_check']=data['all_goodsid_count']/data['all_creditgroupid_nunique']
    data['all_summ_check']=data['all_summ_sum']/data['all_creditgroupid_nunique']
    data['last_day_purchase']=(last_data-data['all_CreditGroupTime_last']).dt.days
    data=data.drop(['all_goodsid_count','all_summ_sum','all_CreditGroupTime_last'],axis=1)
    return data
def month_features(data):
    last_data=data['CreditGroupTime'].max()
    data=data[data['CreditGroupTime']>(last_data-pd.DateOffset(months=1))].reset_index(drop=True)
    args={'creditgroupid':['nunique'],
          'Warehouseid':['nunique'],
          'WarehouseTypeId':[freq],
          'goodsid':['count'],
          'GoodsGroup3Id':[freq,second_freq,third_freq],
          'summ':['sum','mean'],
          'weekend':['mean'],
          'weekday':[freq],
          'hour':['max','min',freq,'std']
          
         }
    new_columns=get_new_columns('month',args)
    data=data.groupby('DiscountCardId').agg(args)
    data.columns=new_columns
    data.reset_index(drop=False,inplace=True)
    data['month_goods_check']=data['month_goodsid_count']/data['month_creditgroupid_nunique']
    data['month_summ_check']=data['month_summ_sum']/data['month_creditgroupid_nunique']
    data=data.drop(['month_goodsid_count','month_summ_sum'],axis=1)
    return data
def last_features(data):
    lst=data.groupby('DiscountCardId')['creditgroupid'].max()
    lst.columns=['lst_check']
    lst=lst.reset_index(drop=False)
    data=lst.merge(data,how='left',on=['creditgroupid','DiscountCardId'])
    args={'WarehouseTypeId':['max'],
          'goodsid':['count'],
          'GoodsGroup3Id':[freq,second_freq],
          'summ':['sum']
        
         }
    new_columns=get_new_columns('lst',args)
    data=data.groupby('DiscountCardId').agg(args)
    data.columns=new_columns
    data.reset_index(drop=False,inplace=True)
#    data=data.drop(['month_goodsid_count','month_summ_sum','month_CreditGroupTime_last'],axis=1)
#    data=data.merge(twogroup,how='left',on='DiscountCardId')
    return data

Wall time: 201 ms

In [3]:
%%time
from keras.preprocessing.sequence import pad_sequences
def goods_label(data):
    itog=np.zeros(len(goods))
    itog[np.unique(data)]=1
    return [itog]
def label_features(data):
    
    ddata=data.groupby(['DiscountCardId'])['GoodsGroup3Id'].agg(goods_label)
    ddata=ddata.reset_index(drop=False)
    ddata.rename(columns={'GoodsGroup3Id':'target'},inplace=True)
 #   data['target']=np.where(data['target'].values>0,1,0)
    return ddata
def all_features(data):
    data=data.groupby(['DiscountCardId'])['GoodsGroup1Id'].agg(lambda x: list(x))
    data=data.reset_index(drop=False) 
    data.rename(columns={'GoodsGroup1Id':'goods'},inplace=True)
#    data=data.groupby('DiscountCardId')['goods'].agg(pad_goods)
#    data=data.groupby('DiscountCardId')['goods'].agg(lambda x:list(x)[::-1])
#    data=data.groupby('DiscountCardId')['goods'].agg(lambda x:[pad_sequences(list(x)[::-1],maxlen=70,padding='post',truncating='post')])
 #   data=data.reset_index(drop=False)
 #   data.rename(columns={'goods':'data'},inplace=True)
    data['goods']=data['goods'].apply(lambda x:np.squeeze(pad_sequences([x],maxlen=400,dtype='int32')))
    return data
def goods_features(data):
    last_data=data['CreditGroupTime'].max()
    args={'creditgroupid':['nunique'],
          'Warehouseid':['nunique'],
          'WarehouseTypeId':[freq],
          'goodsid':['count'],
          'summ':['sum','mean'],
          'Quantity':['mean','std'],
          'weekend':['mean'],
          'weekday':[freq],
          'hour':['max','min',freq,'std'],
          'CreditGroupTime':['last']
         }
    new_columns=get_new_columns('all_goods',args)
    ddata=data.groupby(['DiscountCardId','GoodsGroup3Id']).agg(args)
    ddata.columns=new_columns
    ddata.reset_index(drop=False,inplace=True)
    ddata['all_goods_goods_check']=ddata['all_goods_goodsid_count']/ddata['all_goods_creditgroupid_nunique']
    ddata['all_goods_summ_check']=ddata['all_goods_summ_sum']/ddata['all_goods_creditgroupid_nunique']
    ddata['goods_last_day_purchase']=(last_data-ddata['all_goods_CreditGroupTime_last']).dt.days
    ddata=ddata.drop(['all_goods_goodsid_count','all_goods_summ_sum','all_goods_CreditGroupTime_last'],axis=1)
    data=data[data['CreditGroupTime']>(last_data-pd.DateOffset(months=1))].reset_index(drop=True)
    args={'creditgroupid':['nunique'],
          'Warehouseid':['nunique'],
          'WarehouseTypeId':[freq],
          'goodsid':['count'],
          'summ':['sum','mean'],
          'Quantity':['mean','std'],
          'hour':['max','min',freq,'std']
         }
    new_columns=get_new_columns('month_goods',args)
    data=data.groupby(['DiscountCardId','GoodsGroup3Id']).agg(args)
    data.columns=new_columns
    data.reset_index(drop=False,inplace=True)
    data['month_goods_goods_check']=data['month_goods_goodsid_count']/data['month_goods_creditgroupid_nunique']
    data['month_goods_summ_check']=data['month_goods_summ_sum']/data['month_goods_creditgroupid_nunique']
    data=data.drop(['month_goods_goodsid_count','month_goods_summ_sum'],axis=1)
    ddata=ddata.merge(data,how='left',on=['DiscountCardId','GoodsGroup3Id'])
    return ddata

Using TensorFlow backend.

Wall time: 1.46 s

In [4]:
%%time
import datetime
import h5py
base_date=pd.Timestamp(2018,9,3)
main_data=reduce_mem_usage(data)
inputs=range(54)
def result(i):
    data_period=base_date+pd.DateOffset(weeks=i)
    start_data=data_period-pd.DateOffset(months=3)
    label_period=base_date+pd.DateOffset(weeks=i+1)
    label=main_data[(main_data['CreditGroupTime']>=data_period)&(main_data['CreditGroupTime']<=label_period)].reset_index(drop=True)
    data=main_data[(main_data['CreditGroupTime']>start_data)&(main_data['CreditGroupTime']<data_period)].reset_index(drop=True)
    
#     main=pd.DataFrame({'DiscountCardId':np.repeat(data.DiscountCardId.unique(),len(goods)),
#                        'GoodsGroup3Id':np.tile(goods.GoodsGroup3Id.values,len(data.DiscountCardId.unique()))})
    new_data=all_features(data)
    main=new_data.copy()
    del new_data
    main=main.fillna(0)
    label=label_features(label)
    main=main.merge(label,how='left',on='DiscountCardId')
    main=main.dropna()
    main=reduce_mem_usage(main)
    a=np.asarray([x for x in main['goods']],dtype=np.int16)
    b=np.squeeze(np.asarray([x for x in main['target']],dtype=np.int16))
    main=np.concatenate([a,b],axis=1)
    with h5py.File(f'D:\Projects\Goods_prediction\\real_data\Dat9\data{i}.h5', 'w') as hf:
        hf.create_dataset("data",  data=main)
    print(label_period)
    return print(f'{i} is ready!')
from joblib import Parallel, delayed
par = Parallel(n_jobs=-12)(delayed(result)(i) for i in inputs)
print(par)

Mem. usage decreased to 7446.00 Mb (15.0% reduction)

C:\Users\ToschevikovG.EUROOPT\AppData\Local\Continuum\anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py:706: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  "timeout or by a memory leak.", UserWarning

AxisError: axis 1 is out of bounds for array of dimension 1

In [6]:
import datetime
base_date=pd.Timestamp(2018,9,3)
main_data=reduce_mem_usage(data)
inputs=range(54)
i=53
data_period=base_date+pd.DateOffset(weeks=i)
start_data=data_period-pd.DateOffset(months=3)
label_period=base_date+pd.DateOffset(weeks=i+1)
label=main_data[(main_data['CreditGroupTime']>=data_period)&(main_data['CreditGroupTime']<=label_period)].reset_index(drop=True)
data=main_data[(main_data['CreditGroupTime']>start_data)&(main_data['CreditGroupTime']<data_period)].reset_index(drop=True)

#     main=pd.DataFrame({'DiscountCardId':np.repeat(data.DiscountCardId.unique(),len(goods)),
#                        'GoodsGroup3Id':np.tile(goods.GoodsGroup3Id.values,len(data.DiscountCardId.unique()))})
new_data=all_features(data)
main=new_data.copy()
del new_data
main=main.fillna(0)
label=label_features(label)
main=main.merge(label,how='left',on='DiscountCardId')
main=main.dropna()
a=np.asarray([x for x in main['goods']],dtype=np.int16)
b=np.squeeze(np.asarray([x for x in main['target']],dtype=np.int16))
main=np.concatenate([a,b],axis=1)

Mem. usage decreased to 7446.00 Mb (0.0% reduction)

AxisError: axis 1 is out of bounds for array of dimension 1

array([], dtype=int16)

In [7]:
with h5py.File(f'D:\Projects\Goods_prediction\\real_data\Dat9\data{i}.h5', 'r') as hf:
    data = hf['data'][:]
data

array([[   0,    0,    0, ...,    0,    0,    0],
       [   0,    0,    0, ...,    0,    0,    0],
       [5566, 5566, 2313, ...,    0,    0,    0],
       ...,
       [   0,    0,    0, ...,    0,    0,    0],
       [   0,    0,    0, ...,    0,    0,    0],
       [   0,    0,    0, ...,    0,    0,    0]], dtype=int16)

In [5]:
np.c_[a,b][:,:400]

NameError: name 'i' is not defined